Fix undefined reference to llvm symbols (#55)
We must use the llvm-specific add_library. Instead of doing our own
OBJECT library, we let LLVM do it for us.